export enum WhatsAppConfigurationEndPoint {
    FETCH_WHATSAPP_CONFIG = 'meta/whatsapp',
    CREATE_WHATSAPP_CONFIG = 'meta/whatsapp/create',
    EDIT_WHATSAPP_CONFIG = 'meta/whatsapp/edit',
    DELETE_WHATSAPP_CONFIG = 'meta/whatsapp/delete',

    FETCH_WHATSAPP_NUMBERS = 'meta/whatsapp/numbers',
    FETCH_WHATSAPP_NUMBER = 'meta/whatsapp/number',
    DELETE_WHATSAPP_NUMBER = 'meta/whatsapp/number/delete',
    CREATE_WHATSAPP_NUMBER = 'meta/whatsapp/number/create',
    EDIT_WHATSAPP_NUMBER = 'meta/whatsapp/number/edit'
}

export enum WhatsAppConfigurationQueryKey {
    FETCH_WHATSAPP_CONFIG = 'FETCH_WHATAPP_CONFIG',
    CREATE_WHATSAPP_CONFIG = 'CREATE_WHATSAPP_CONFIG',
    EDIT_WHATSAPP_CONFIG = 'EDIT_WHATSAPP_CONFIG',
    DELETE_WHATSAPP_CONFIG = 'DELETE_WHATSAPP_CONFIG',

    FETCH_WHATSAPP_NUMBERS = 'FETCH_WHATSAPP_NUMBERS',
    FETCH_WHATSAPP_NUMBER = 'FETCH_WHATSAPP_NUMBER',
    DELETE_WHATSAPP_NUMBER = 'DELETE_WHATSAPP_NUMBER',
    CREATE_WHATSAPP_NUMBER = 'CREATE_WHATSAPP_NUMBER',
    EDIT_WHATSAPP_NUMBER = 'EDIT_WHATSAPP_NUMBER'
}