version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5
    assignees:
      - "koppreshk"
    reviewers:
      - "koppreshk"
    labels:
      - "dependencies"
      - "npm"
    versioning-strategy: "increase"
    ignore:
      # Ignore major updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Ignore patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]