version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5
    assignees:
      - "koppreshk"
    reviewers:
      - "koppreshk"
    labels:
      - "dependencies"
      - "npm"
    package-manager: "yarn"
    # Security updates configuration
    allow:
      - dependency-type: "direct"
        dependency-name: "*"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Ensure yarn.lock is updated
    commit-message:
      prefix: "chore"
      include: "scope"