export enum InstagramConfigurationEndPoint {
    FETCH_INSTAGRAM_CONFIGURATION = 'meta/instagram',
    CREATE_INSTAGRAM_CONFIGURATION = 'meta/instagram/create',
    DELETE_INSTAGRAM_CONFIGURATION = 'meta/instagram/delete',   
}

export enum InstagramConfigurationQueryKey {
    FETCH_INSTAGRAM_CONFIGURATION = 'FETCH_INSTAGRAM_CONFIGURATION',
    CREATE_INSTAGRAM_CONFIGURATION = 'CREATE_INSTAGRAM_CONFIGURATION',
    DELETE_INSTAGRAM_CONFIGURATION = 'DELETE_INSTAGRAM_CONFIGURATION',
}