export const InstagramConfigurationEndPoint = {
  FETCH_INSTAGRAM_CONFIGURATION: 'meta/instagram',
  CREATE_INSTAGRAM_CONFIGURATION: 'meta/instagram/create',
  EDIT_INSTAGRAM_CONFIGURATION: 'meta/instagram/edit',
  DELETE_INSTAGRAM_CONFIGURATION: 'meta/instagram/delete',
} as const;

export const InstagramConfigurationQueryKey = {
  FETCH_INSTAGRAM_CONFIGURATION: 'FETCH_INSTAGRAM_CONFIGURATION',
  CREATE_INSTAGRAM_CONFIGURATION: 'CREATE_INSTAGRAM_CONFIGURATION',
  EDIT_INSTAGRAM_CONFIGURATION: 'EDIT_INSTAGRAM_CONFIGURATION',
  DELETE_INSTAGRAM_CONFIGURATION: 'DELETE_INSTAGRAM_CONFIGURATION',
} as const;
