export const EscalationEndPoint = {
  FETCH_SLA_METADATA: 'sla/fetch_options_for_sla',
  FETCH_ALL_ESCALATIONS_NEW: 'sla/all',
  DELETE_ESCALATION_NEW: 'sla/delete',
  CREATE_ESCALATION_NEW: 'sla/create',
  FETCH_ESCALATION_BY_ID: 'sla',
  SET_ESCALATION_STATUS: 'sla/status',
  EDIT_ESCALATION_NEW: 'sla/edit',
  FETCH_ALL_QUEUES: 'queues',
} as const;

export const EscalationQueryKey = {
  FETCH_SLA_METADATA: 'FETCH_SLA_METADATA',
  FETCH_ALL_ESCALATIONS_NEW: 'FETCH_ALL_ESCALATIONS_NEW',
  DELETE_ESCALATION_NEW: 'DELETE_ESCALATION_NEW',
  CREATE_ESCALATION_NEW: 'CREATE_ESCALATION_NEW',
  FETCH_ESCALATION_BY_ID: 'FETCH_ESCALATION_BY_ID',
  SET_ESCALATION_STATUS: 'SET_ESCALATION_STATUS',
  EDIT_ESCALATION_NEW: 'EDIT_ESCALATION_NEW',
  FETCH_ALL_QUEUES: 'FETCH_ALL_QUEUES',
} as const;
