import { UserList } from "modules/settings/component/general/users/user-list"

const data = [{ "userId": 1, "firstName": "Cornell", "lastName": "Gonzalo", "email": "cgonzalo0@ftc.gov", "role": "Agent" },
{ "userId": 2, "firstName": "Ash", "lastName": "Peirazzi", "email": "apeirazzi1@1und1.de", "role": "Admin" },
{ "userId": 3, "firstName": "Quintus", "lastName": "Humpage", "email": "qhumpage2@vistaprint.com", "role": "Admin" },
{ "userId": 4, "firstName": "Kele", "lastName": "Suter", "email": "ksuter3@adobe.com", "role": "Admin" },
{ "userId": 5, "firstName": "Dew", "lastName": "Aronowitz", "email": "daronowitz4@dailymail.co.uk", "role": "Agent" },
{ "userId": 6, "firstName": "Ray", "lastName": "Petto", "email": "rpetto5@nbcnews.com", "role": "Admin" },
{ "userId": 7, "firstName": "Dasi", "lastName": "Rafferty", "email": "drafferty6@skyrock.com", "role": "Agent" },
{ "userId": 8, "firstName": "Chadd", "lastName": "Fawlo", "email": "cfawlo7@technorati.com", "role": "Agent" },
{ "userId": 9, "firstName": "Cooper", "lastName": "McIlraith", "email": "cmcilraith8@bloglines.com", "role": "Agent" },
{ "userId": 10, "firstName": "Charlena", "lastName": "Hastwall", "email": "chastwall9@tripadvisor.com", "role": "Admin" },
{ "userId": 11, "firstName": "Inness", "lastName": "Bobasch", "email": "ibobascha@cdc.gov", "role": "Agent" },
{ "userId": 12, "firstName": "Reine", "lastName": "Jirzik", "email": "rjirzikb@addthis.com", "role": "Agent" },
{ "userId": 13, "firstName": "Alfy", "lastName": "Brugsma", "email": "abrugsmac@oaic.gov.au", "role": "Agent" },
{ "userId": 14, "firstName": "Leupold", "lastName": "Ivanishin", "email": "livanishind@naver.com", "role": "Agent" },
{ "userId": 15, "firstName": "Emilee", "lastName": "Derell", "email": "ederelle@com.com", "role": "Admin" },
{ "userId": 16, "firstName": "Sallyann", "lastName": "Blore", "email": "sbloref@usatoday.com", "role": "Admin" },
{ "userId": 17, "firstName": "Wes", "lastName": "Folonin", "email": "wfoloning@google.it", "role": "Admin" },
{ "userId": 18, "firstName": "Lottie", "lastName": "Fussie", "email": "lfussieh@businessweek.com", "role": "Admin" },
{ "userId": 19, "firstName": "Drugi", "lastName": "Colvin", "email": "dcolvini@boston.com", "role": "Agent" },
{ "userId": 20, "firstName": "Collete", "lastName": "Wohler", "email": "cwohlerj@homestead.com", "role": "Admin" },
{ "userId": 21, "firstName": "Pinchas", "lastName": "Arnaudot", "email": "parnaudotk@tinyurl.com", "role": "Agent" },
{ "userId": 22, "firstName": "Milena", "lastName": "Wallice", "email": "mwallicel@vk.com", "role": "Agent" },
{ "userId": 23, "firstName": "Ursala", "lastName": "Ledley", "email": "uledleym@icio.us", "role": "Admin" },
{ "userId": 24, "firstName": "Marcelo", "lastName": "Harbor", "email": "mharborn@netlog.com", "role": "Agent" },
{ "userId": 25, "firstName": "Marlene", "lastName": "Mahedy", "email": "mmahedyo@mac.com", "role": "Admin" },
{ "userId": 26, "firstName": "Idalina", "lastName": "Tieman", "email": "itiemanp@163.com", "role": "Admin" },
{ "userId": 27, "firstName": "Sylvester", "lastName": "Tiley", "email": "stileyq@eventbrite.com", "role": "Agent" },
{ "userId": 28, "firstName": "Enrique", "lastName": "Espadater", "email": "eespadaterr@stanford.edu", "role": "Admin" },
{ "userId": 29, "firstName": "Tandie", "lastName": "Tungate", "email": "ttungates@tinypic.com", "role": "Admin" },
{ "userId": 30, "firstName": "Ilene", "lastName": "Godwin", "email": "igodwint@alibaba.com", "role": "Agent" },
{ "userId": 31, "firstName": "Cos", "lastName": "Rasher", "email": "crasheru@mail.ru", "role": "Agent" },
{ "userId": 32, "firstName": "Dedie", "lastName": "Pree", "email": "dpreev@wunderground.com", "role": "Agent" },
{ "userId": 33, "firstName": "Michel", "lastName": "Ivanilov", "email": "mivanilovw@wiley.com", "role": "Agent" },
{ "userId": 34, "firstName": "Jud", "lastName": "Peoples", "email": "jpeoplesx@youtube.com", "role": "Admin" },
{ "userId": 35, "firstName": "Dane", "lastName": "Barthelemy", "email": "dbarthelemyy@example.com", "role": "Admin" },
{ "userId": 36, "firstName": "Beniamino", "lastName": "Minton", "email": "bmintonz@unicef.org", "role": "Admin" },
{ "userId": 37, "firstName": "Mariette", "lastName": "Gostage", "email": "mgostage10@rambler.ru", "role": "Admin" },
{ "userId": 38, "firstName": "Joyann", "lastName": "Haddy", "email": "jhaddy11@networksolutions.com", "role": "Agent" },
{ "userId": 39, "firstName": "Cass", "lastName": "Overell", "email": "coverell12@earthlink.net", "role": "Agent" },
{ "userId": 40, "firstName": "Wenona", "lastName": "Dudhill", "email": "wdudhill13@answers.com", "role": "Admin" },
{ "userId": 41, "firstName": "Marleen", "lastName": "Jotcham", "email": "mjotcham14@tripod.com", "role": "Admin" },
{ "userId": 42, "firstName": "Petronille", "lastName": "Collimore", "email": "pcollimore15@alexa.com", "role": "Agent" },
{ "userId": 43, "firstName": "Cara", "lastName": "Spillman", "email": "cspillman16@intel.com", "role": "Agent" },
{ "userId": 44, "firstName": "Krissie", "lastName": "Koppke", "email": "kkoppke17@example.com", "role": "Admin" },
{ "userId": 45, "firstName": "Brendis", "lastName": "Inkpen", "email": "binkpen18@bandcamp.com", "role": "Agent" },
{ "userId": 46, "firstName": "Adeline", "lastName": "Pugh", "email": "apugh19@purevolume.com", "role": "Agent" },
{ "userId": 47, "firstName": "Ruby", "lastName": "Wynrehame", "email": "rwynrehame1a@blinklist.com", "role": "Admin" },
{ "userId": 48, "firstName": "Micki", "lastName": "Santry", "email": "msantry1b@istockphoto.com", "role": "Admin" },
{ "userId": 49, "firstName": "Siana", "lastName": "Crosskill", "email": "scrosskill1c@weebly.com", "role": "Agent" },
{ "userId": 50, "firstName": "Anet", "lastName": "Agglio", "email": "aagglio1d@sciencedaily.com", "role": "Admin" }]

export const GetUsersContainer = () => {
    return (
        <>
            <UserList usersData={data} />
        </>
    )
}