import { AllCustomers } from '../components/all-customers';

const data = [
  {
    customerId: 1,
    name: 'Cynthy Ciccottio',
    email: 'cciccottio0@e-recht24.de',
    customerGroup: 'Y-Solowarm',
    status: 'bifurcated',
  },
  {
    customerId: 2,
    name: 'Charita Woolfoot',
    email: 'cwoolfoot1@theatlantic.com',
    customerGroup: 'Quo Lux',
    status: 'success',
  },
  {
    customerId: 3,
    name: 'Muffin Wybrow',
    email: 'mwybrow2@bizjournals.com',
    customerGroup: 'Cookley',
    status: 'Distributed',
  },
  {
    customerId: 4,
    name: 'Barbie Stooders',
    email: 'bstooders3@wordpress.com',
    customerGroup: 'Prodder',
    status: 'regional',
  },
  {
    customerId: 5,
    name: 'Brook Kohrt',
    email: 'bkohrt4@livejournal.com',
    customerGroup: 'Flexidy',
    status: '6th generation',
  },
  {
    customerId: 6,
    name: 'Sheela Elecum',
    email: 'selecum5@so-net.ne.jp',
    customerGroup: 'Zathin',
    status: 'Total',
  },
  {
    customerId: 7,
    name: 'Iorgos McColgan',
    email: 'imccolgan6@ucsd.edu',
    customerGroup: 'Cookley',
    status: 'alliance',
  },
  {
    customerId: 8,
    name: 'Brooks Ecclesall',
    email: 'becclesall7@clickbank.net',
    customerGroup: 'Hatity',
    status: 'solution',
  },
  {
    customerId: 9,
    name: 'Jeniece Busch',
    email: 'jbusch8@hao123.com',
    customerGroup: 'Subin',
    status: 'protocol',
  },
  {
    customerId: 10,
    name: 'Andreana Tomankowski',
    email: 'atomankowski9@vimeo.com',
    customerGroup: 'Sonair',
    status: 'disintermediate',
  },
  {
    customerId: 11,
    name: "Alejandro O'Geneay",
    email: 'aogeneaya@samsung.com',
    customerGroup: 'Duobam',
    status: 'Progressive',
  },
  {
    customerId: 12,
    name: 'Hughie Lefort',
    email: 'hlefortb@github.com',
    customerGrouap: 'Ronstring',
    status: 'Cross-platform',
  },
  {
    customerId: 13,
    name: 'Tabbitha Kmieciak',
    email: 'tkmieciakc@bloglines.com',
    customerGroup: 'Latlux',
    status: 'Open-architected',
  },
  {
    customerId: 14,
    name: 'Monro Laddle',
    email: 'mladdled@deviantart.com',
    customerGroup: 'Tampflex',
    status: 'focus group',
  },
  {
    customerId: 15,
    name: 'Fidela Lermit',
    email: 'flermite@altervista.org',
    customerGroup: 'Overhold',
    status: 'bi-directional',
  },
  {
    customerId: 16,
    name: 'Dionisio Kupis',
    email: 'dkupisf@is.gd',
    customerGroup: 'Cardify',
    status: 'infrastructure',
  },
  {
    customerId: 17,
    name: 'Fredelia Galbraeth',
    email: 'fgalbraethg@usa.gov',
    customerGroup: 'Latlux',
    status: 'Quality-focused',
  },
  {
    customerId: 18,
    name: 'Sax Biasi',
    email: 'sbiasih@spiegel.de',
    customerGroup: 'Tampflex',
    status: 'discrete',
  },
  {
    customerId: 19,
    name: 'Danna Kelleway',
    email: 'dkellewayi@aboutads.info',
    customerGroup: 'Y-find',
    status: 'global',
  },
  {
    customerId: 20,
    name: 'Gustave Pothbury',
    email: 'gpothburyj@fotki.com',
    customerGroup: 'Ronstring',
    status: 'value-added',
  },
  {
    customerId: 21,
    name: 'Claus Johanchon',
    email: 'cjohanchonk@miitbeian.gov.cn',
    customerGroup: 'Transcof',
    status: 'optimal',
  },
  {
    customerId: 22,
    name: 'Susie Holyard',
    email: 'sholyardl@odnoklassniki.ru',
    customerGroup: 'Sonair',
    status: 'stable',
  },
  {
    customerId: 23,
    name: 'Aubrey Cammacke',
    email: 'acammackem@state.gov',
    customerGroup: 'Otcom',
    status: 'portal',
  },
  {
    customerId: 24,
    name: 'Lewes Skin',
    email: 'lskinn@ibm.com',
    customerGroup: 'Transcof',
    status: 'Multi-layered',
  },
  {
    customerId: 25,
    name: 'Prudence Lloyds',
    email: 'plloydso@nydailynews.com',
    customerGroup: 'Job',
    status: 'Up-sized',
  },
  {
    customerId: 26,
    name: 'Freida McRobb',
    email: 'fmcrobbp@clickbank.net',
    customerGroup: 'Voltsillam',
    status: 'Horizontal',
  },
  {
    customerId: 27,
    name: 'Nicola Lates',
    email: 'nlatesq@fda.gov',
    customerGroup: 'Stronghold',
    status: 'Adaptive',
  },
  {
    customerId: 28,
    name: 'Jillayne Densumbe',
    email: 'jdensumber@fda.gov',
    customerGroup: 'Tampflex',
    status: 'even-keeled',
  },
  {
    customerId: 29,
    name: 'Larisa Habishaw',
    email: 'lhabishaws@youtube.com',
    customerGroup: 'Keylex',
    status: 'disintermediate',
  },
  {
    customerId: 30,
    name: 'Rollie Omar',
    email: 'romart@umn.edu',
    customerGroup: 'Matsoft',
    status: 'utilisation',
  },
  {
    customerId: 31,
    name: 'Shepard Beine',
    email: 'sbeineu@so-net.ne.jp',
    customerGroup: 'Otcom',
    status: 'firmware',
  },
  {
    customerId: 32,
    name: 'Jillian Baffin',
    email: 'jbaffinv@vinaora.com',
    customerGroup: 'Vagram',
    status: 'process improvement',
  },
  {
    customerId: 33,
    name: 'Arielle Howkins',
    email: 'ahowkinsw@desdev.cn',
    customerGroup: 'It',
    status: 'function',
  },
  {
    customerId: 34,
    name: 'Teressa Episcopio',
    email: 'tepiscopiox@un.org',
    customerGroup: 'Ronstring',
    status: 'model',
  },
  {
    customerId: 35,
    name: 'Mariellen Tweede',
    email: 'mtweedey@google.co.jp',
    customerGroup: 'Rank',
    status: 'Decentralized',
  },
  {
    customerId: 36,
    name: 'Cassey Rapp',
    email: 'crappz@github.io',
    customerGroup: 'Fintone',
    status: 'national',
  },
  {
    customerId: 37,
    name: 'Rollie Warricker',
    email: 'rwarricker10@businesswire.com',
    customerGroup: 'Mat Lam Tam',
    status: 'holistic',
  },
  {
    customerId: 38,
    name: 'Melissa Duddan',
    email: 'mduddan11@squarespace.com',
    customerGroup: 'Subin',
    status: 'Reduced',
  },
  {
    customerId: 39,
    name: 'Verla Barns',
    email: 'vbarns12@ow.ly',
    customerGroup: 'Flexidy',
    status: 'eco-centric',
  },
  {
    customerId: 40,
    name: 'Herc Braferton',
    email: 'hbraferton13@amazon.com',
    customerGroup: 'Fixflex',
    status: 'database',
  },
  {
    customerId: 41,
    name: 'Naomi Placide',
    email: 'nplacide14@google.com.hk',
    customerGroup: 'Zaam-Dox',
    status: 'Profit-focused',
  },
  {
    customerId: 42,
    name: 'Darlleen Garms',
    email: 'dgarms15@topsy.com',
    customerGroup: 'Zontrax',
    status: 'Triple-buffered',
  },
  {
    customerId: 43,
    name: 'Meta Brotherick',
    email: 'mbrotherick16@pinterest.com',
    customerGroup: 'Cookley',
    status: 'productivity',
  },
  {
    customerId: 44,
    name: 'Nomi Aulds',
    email: 'naulds17@nationalgeographic.com',
    customerGroup: 'Cookley',
    status: 'Robust',
  },
  {
    customerId: 45,
    name: 'Felicle Izakson',
    email: 'fizakson18@php.net',
    customerGroup: 'Cardguard',
    status: 'even-keeled',
  },
  {
    customerId: 46,
    name: 'Yank Genever',
    email: 'ygenever19@angelfire.com',
    customerGroup: 'Aerified',
    status: 'Graphic Interface',
  },
  {
    customerId: 47,
    name: 'Aindrea Murrison',
    email: 'amurrison1a@noaa.gov',
    customerGroup: 'Y-Solowarm',
    status: 'Distributed',
  },
  {
    customerId: 48,
    name: 'Viva Pitcher',
    email: 'vpitcher1b@epa.gov',
    customerGroup: 'Flexidy',
    status: 'modular',
  },
  {
    customerId: 49,
    name: 'Joete Haddrill',
    email: 'jhaddrill1c@ehow.com',
    customerGroup: 'Tin',
    status: 'Optional',
  },
  {
    customerId: 50,
    name: 'Aguste Dellatorre',
    email: 'adellatorre1d@upenn.edu',
    customerGroup: 'Wrapsafe',
    status: 'Profit-focused',
  },
];

export const AllCustomersContainer = () => {
  return <AllCustomers data={data} />;
};
