export enum TicketPermissionKeys {
    ADD_TICKET = 'ADD_TICKET',
    REPLY_TICKET = 'REPLY_TICKET',
    EDIT_PRIORITY = 'EDIT_PRIORITY',
    EDIT_ASSIGNEE = 'EDIT_ASSIGNEE',
    EDIT_STATUS = 'EDIT_STATUS',
    EDIT_TAGS = 'EDIT_TAGS',
    SPLIT_TICKET = 'SPLIT_TICKET',
    MANAGE_NOTES = 'MANAGE_NOTES',
    MERGE_TICKET = 'MERGE_TICKET',
}

export enum ConfigurationPermissionKeys {
    MANAGE_TICKET_STATUS = 'MANAGE_TICKET_STATUS',
    MANAGE_TAGS = 'MANAGE_TAGS',
    MANAGE_EMAIL = 'MANAGE_EMAIL',
    MANAGE_TICKET_ESCALATION = 'MANAGE_TICKET_ESCALATION',
    MANAGE_AUTO_ASSIGNMENTS = 'MANAGE_AUTO_ASSIGNMENTS',
    MANAGE_CREATE_TICKET_TRIGGERS = 'MANAGE_CREATE_TICKET_TRIGGERS',
    MANAGE_UPDATE_TICKET_TRIGGERS = 'MANAGE_UPDATE_TICKET_TRIGGERS',
    MANAGE_AGENTS = 'MANAGE_AGENTS',
    MANAGE_QUEUES = 'MANAGE_QUEUES',
    MANAGE_ROLES_PERMISSIONS = 'MANAGE_ROLES_PERMISSIONS',
    MANAGE_AGENT_AVAILABILITY_STATUSES = 'MANAGE_AGENT_AVAILABILITY_STATUSES',
    MANAGE_AUDIT_LOGS = 'MANAGE_AUDIT_LOGS',
    MANAGE_MARKETPLACE = 'MANAGE_MARKETPLACE'
}

export type AllPermissionKeys = TicketPermissionKeys | ConfigurationPermissionKeys;

export enum ModuleKeys {
    TICKETS = 'TICKETS',
    CONFIGURATIONS = 'CONFIGURATIONS',
    DASHBOARDS = 'DASHBOARDS'
}
