export enum FacebookConfigurationEndPoint {
    CREATE_FACEBOOK_CONFIGURATION = 'meta/facebook/create',
    FETCH_FACEBOOK_CONFIGURATION = 'meta/facebook/account',
    DELETE_FACEBOOK_CONFIGURATION = 'meta/facebook/delete'
}

export enum FacebookConfigurationQueryKey {
    CREATE_FACEBOOK_CONFIGURATION = 'CREATE_FACEBOOK_CONFIGURATION',
    FETCH_FACEBOOK_CONFIGURATION = 'FETCH_FACEBOOK_CONFIGURATION',
    DELETE_FACEBOOK_CONFIGURATION = 'DELETE_FACEBOOK_CONFIGURATION'
}